[[redirects]]
  from = "/api/*"
  to = "https://chat-app-xsxm.onrender.com/api/:splat"
  status = 307
  force = true
  headers = {Access-Control-Allow-Origin = "*"}


[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/api/*"
[headers.values]
Access-Control-Allow-Origin = "*"

